export var ATFBuilder = Class.create();
ATFBuilder.prototype = {
    initialize: function() {},

    build: function(stepDefs) {
        if (!GlidePluginManager.isActive('com.snc.test_management2')) {
            return { suiteId: null, testId: null, error: 'ATF plugin (com.snc.test_management2) is not active on this instance' };
        }

        var suiteId = this._createSuite();
        if (!suiteId) {
            return { suiteId: null, testId: null, error: 'Failed to create ATF suite' };
        }

        var testId = this._createTest(suiteId);
        if (!testId) {
            return { suiteId: suiteId, testId: null, error: 'Failed to create ATF test' };
        }

        for (var i = 0; i < stepDefs.length; i++) {
            this._createStep(testId, stepDefs[i], i + 1);
        }

        return { suiteId: suiteId, testId: testId, error: null };
    },

    _createSuite: function() {
        var gr = new GlideRecord('sys_atf_suite');
        gr.initialize();
        gr.setValue('name', 'SDLC AI - Generated Suite ' + new GlideDateTime().getDisplayValue());
        gr.setValue('description', 'Auto-generated by SDLC AI Orchestrator');
        return gr.insert();
    },

    _createTest: function(suiteId) {
        var gr = new GlideRecord('sys_atf_test');
        gr.initialize();
        gr.setValue('name', 'SDLC AI - Generated Test');
        gr.setValue('description', 'Auto-generated by SDLC AI Orchestrator');
        gr.setValue('sys_atf_suite', suiteId);
        return gr.insert();
    },

    _createStep: function(testId, stepDef, order) {
        var configId = this._resolveStepConfig(stepDef.step_type, stepDef.action);
        if (!configId) { return; }

        var gr = new GlideRecord('sys_atf_step');
        gr.initialize();
        gr.setValue('test', testId);
        gr.setValue('order', order * 100);
        gr.setValue('step_config', configId);
        gr.setValue('description', stepDef.description || '');

        var inputs = {};
        if (stepDef.step_type === 'server' && stepDef.script) {
            inputs.script = stepDef.script;
        } else if (stepDef.table) {
            inputs.table = stepDef.table;
        }
        if (Object.keys(inputs).length > 0) {
            gr.setValue('inputs', JSON.stringify(inputs));
        }

        gr.insert();
    },

    _resolveStepConfig: function(stepType, action) {
        var configMap = {
            'form.open':           'Open a Form',
            'form.submit':         'Submit a Form',
            'form.set_field':      'Set Field Values',
            'server.run_script':   'Run Server Side Script',
            'server.assert_record':'Assert Record Field Values',
        };

        var key = stepType + '.' + action;
        var sysName = configMap[key];
        if (!sysName) { return null; }

        var gr = new GlideRecord('sys_atf_step_config');
        gr.addQuery('sys_name', sysName);
        gr.setLimit(1);
        gr.query();
        return gr.next() ? gr.getUniqueValue() : null;
    },

    type: 'ATFBuilder',
};
